-- AssetCore seed data from Dokumentasi IT Support by MMI.xlsx
DELETE FROM ac_asset_software WHERE asset_id IN (SELECT id FROM ac_assets WHERE notes='[seeded]');
DELETE FROM ac_assets WHERE notes='[seeded]';
DELETE FROM ac_infrastructure WHERE condition_notes='[seeded]';
DELETE FROM ac_licenses WHERE notes='[seeded]';
DELETE FROM ac_subscriptions WHERE notes='[seeded]';

-- Laptop / PC
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Ismail' LIMIT 1),'Laptop','Lenovo','W 11 Pro','MAK (Volume)','I7-7600','16 GB','512 GB','ProPlus 21 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Eclips');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'VS Code');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Dbeaver');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'MongoDB Compas');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Sourcetree');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinSCP');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'iReport');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Oracle');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'SQL Server');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'PostgreSQL');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FortiClient');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'ZeroTier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Docker Desktop');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Riana Rifki' LIMIT 1),'Laptop','Lenovo','W 11 Home','Digital License OEM','Ryzen 5 5600U','16 GB','512 GB','ProPlus 19 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'DBeaver');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FortiClient');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Anydesk');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Adobe Acrobat');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Devina Amanda Putri' LIMIT 1),'Laptop','Lenovo','W 11 Pro','MAK (Volume)','i5-10210U','20 GB','512 GB','ProPlus 19 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'DBeaver');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Oracle');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Netbeans');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Filezilla');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'MySQL Server 8.0');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'RabbitMQ');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinSCP');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Ahmad Sauki' LIMIT 1),'Laptop','Lenovo','W 11 Pro','MAK (Volume)','I7-1165G7','24 GB','1TB NVME + 500','ProPlus 16 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FortiClient');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'CheckPoint Endpoint Security VPN');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'VSCode');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Eclips');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FileZilla');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'MongoDB');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Docker Desktop');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Tibco Jaspersoft');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'VSCode');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WebEX');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visual Studio');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Vita Apriliana' LIMIT 1),'Laptop','Lenovo','W 11 Home','Digital License','I5-1035G1','20 GB','1TB NVME','365 Enterprise (KMS MMI)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'VSCode');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Eclips');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FileZilla');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'pgAdmin');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'PostgreSQL');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Python');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'SourceTree');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Telegram');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'XAMPP');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'ZeroTier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Anydesk');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'MySQL Server 8.0');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'RabbitMQ');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Windi Rahmawati' LIMIT 1),'Laptop','Lenovo','W 11 Home','Digital License','I7-1355U','40 GB','512 GB','Office Home 2021','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Docker Desktop');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FortiClient');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Intellij');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'RabbitMQ');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinSCP');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'XAMPP');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Khonza Izzati' LIMIT 1),'Laptop','Lenovo','W 10 Pro','Digital License','I5-6300U','16 GB','512 GB','ProPlus 2021 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FortiClient');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visual Paradigm');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Lightshot');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Sudiatila Lavandria' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License OEM','I3-10110U','8 GB','256 + 1TB HDD','365 Enterprise (KMS MMI)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Adobe Acr PDF');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visio & Project');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Winrar');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zoom');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Reni Sunjastri' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License','I3-10110U','8 GB','256 NVME','365 enterprise (hr_mmi @outlook.com)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Adobe Acr PDF');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visio & Project');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Winrar');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zoom');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Jundi Aufa Robbani' LIMIT 1),'Laptop','Lenovo','Win 11 Pro','Digital License','I7-6300U','16 GB','512 SSD Sata','365 Enterprise (KMS MMI)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'DBeaver');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FortiClient');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Intelijj');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'iReport');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Laragon 8.1.0');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visual Studi Code');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'MobaXterm');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postgree');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'RabbitMQ');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'SourceTree');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinSCP');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Yoshfia Abie Zaky' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License','Ultra 5 225H','16 GB','512 GB','Office Home 2024','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'MobaXtrem');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'VSC');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Intelij');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Anydesk');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Dbeaver');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Docker Desktop');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Nurul Emilia' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License','Ultra 5 225H','16 GB','512 GB','Office Home 2024','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Global Protect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Bamara Anugrah A.P' LIMIT 1),'Laptop','Lenovo','Win 11 Pro','Digital License','I5-10210U','20 GB','512 GB','Pro Plus 21 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Dbeaver');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Figma');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinSCP');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Balsamiq Mockups 3');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visual Paradigm for UML 10.2');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Siti Nurbaity' LIMIT 1),'Laptop','Lenovo','Win 11 Pro','Digital License','I5-10210U','8 GB','512 + 256 SSD','Office Mondo 2016 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Eclips');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'AquaData');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FortiClient');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FileZilla');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'BIG IP EDFE Client');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'iReport');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Microsoft Visual Studio');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Power BI');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Phyton');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Softether');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'TeamViewer');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'UltraViewer');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visual Paradigm');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'XAMPP');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Dedek Darmadi' LIMIT 1),'Laptop','Lenovo','Win 11 Pro','MAK (Volume)','I5-10210U','12 GB','256 + 256 NVME','ProPlus 2019 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visual Paradigm');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Figma');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'MongoDB');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Nitro');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Feri Widiyanto' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License','Ultra 5 225H','16 GB','512 GB','Office Home 2024','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Oracle');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'PostgreSQL');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinSCP');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visual Studio Code');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Muhammad Faiz Rizza Mubarak' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License','Ultra 5 225H','16 GB','512 GB','Office Home 2024','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobaProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FortiClient');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Foxit');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Anydesk');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'mRemoteMG');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Checkpoint VPN');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Amalia Wahyuni' LIMIT 1),'Laptop','Lenovo','Win 10 Pro','Digital License','I5-4210M','16 GB','256 GB','Pro Plus 2010 (not Actived)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Adobe Acrobat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Foxit');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES(NULL,'Laptop','Lenovo','Win 11 Home','Digital License','I3-1215U','16 GB','512 NMVE','Office 365 (faiz@  mitramandiri.co.id)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Adobe Acrobat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinRAR');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Mahmud Kusbiantora' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License OEM','I7-1355U','16 GB','1TB NVME','Office 365 (fa.mmi  @outlook.com)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Efaktur');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'ESPT2114');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Espt PPh Badan');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Fina Software');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinRAR');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Rizky Aditya' LIMIT 1),'Laptop','Lenovo','Win 10 Pro','Digital License','I3-8145U','8 GB','512 GB','Office 365 (fa.mmi  @outlook.com)  +  Pro Plus 19 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Adobe Acrobat');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Reonaldo Galen (ex-Edwin)' LIMIT 1),'Laptop','Lenovo','Win 11 Home + Ubuntu 25','Digital License','I5-1035G1','20 GB','512 NVME','-','Baik','[seeded]');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Tri Wijiyati' LIMIT 1),'Laptop','Lenovo','Win 10 Pro','Digital License','A9-9425','8 GB','256 + 1TB HDD','Pro Plus 2019 (KMS)','Baik','[seeded]');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Dwitya Damayanti' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License OEM','Ryzen 5 5500U','8 GB','500 GB','Pro Plus 2019 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Adobe Acrobat');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Melinda Luvita' LIMIT 1),'Laptop','Asus','Win 11 Home','Digital License OEM','I5-1235U','16 GB','512 GB','Office Home 2021','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Adobe Acrobat');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Farhan Nurtiansyah' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License OEM','I5-1235U','16 GB','512 GB','Office Home 2021  +  Visio Pro 21/24 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Adobe Acrobat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'OBS');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Figma');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Aisyah Nur Aliyah' LIMIT 1),'Laptop','Lenovo','Win 11 Pro','MAK (Volume)','I5-10210U','20 GB','512 GB','Office 365 (eliya.aivey @gmail.com – pribadi)  +  Pro/Visio/Project Plus (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Docker Desktop');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Dbeaver');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'FortiClient');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'iReport');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'MongoDB');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'MySQL Workbench');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Putty');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'RabbitMQ');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'SourceTree');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinSCP');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Faiz Shidqi Agasa' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License','I7-13620H +  + +  RTX 4060','32 GB','1TB NVME','Office Home 2024','Baik','[seeded]');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Raden Rizky Aria Putra W' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License','I5-1240P','16 GB','512 GB','Office 365 Pro Plus (no lisensi)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Dbeaver');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Docker Desktop');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Eclipse');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'OpeVPN');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'PuTTY');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'SourceTree');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinSCP');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Dwi Wahyuni Santoso' LIMIT 1),'Laptop','Lenovo','Win 10 Pro','MAK (Volume)','I3-8145U','12 GB','512 GB','Pro Plus 2016 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Dbeaver');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Faststone');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Figma');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'JDK 121');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Postman');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'WinSCP');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Balsamiq Mockups 3');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visual Paradigm for UML 10.2');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Aris Cahyaji' LIMIT 1),'Laptop','Lenovo','Win 11 Pro','Digital License OEM','I5-1335U','16 GB','512 NVME','Office Home 2019  +  Pro/Visio/Project Plus (KMS)','Baik','[seeded]');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Jemmy Newton' LIMIT 1),'Laptop','Lenovo','Win 11 Pro','Digital License','I5-6300U','12 GB','512 GB','Pro/Visio/Project Plus 2021 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Andhy Ardhianto' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License','Ryzen 5 5625U','8 GB','512 GB','Office 365 + Pro/Visio/Project 2021 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Chairul Umam' LIMIT 1),'Laptop','Lenovo','Win 11 Pro','Digital License','i3-1115G4','8 GB','512 GB','Office 365  (Pribadi) + Pro/Visio/Project 2021 (KMS)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Amalia' LIMIT 1),'Laptop','Lenovo','Win 11 Home','Digital License','i5-10210U','16 GB','256 GB','Office 365 (mmi@ thunder.origin365.pro)','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Navicat');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Zerotier');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'GlobalProtect');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Java SDK 121');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Teddy Octavian Pramana' LIMIT 1),'Laptop','Asus','Win 11 Home','Digital License','i7-1355U','16 GB','512 GB','Office 365','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Visio');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Office Timeline');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Project');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Indah Taraullya' LIMIT 1),'Laptop','Lenovo Thinkpad','Win 11 Pro','Digital License','15-4300U','12 GB','256 GB','Office 365 (mmioffice3651)','Baik','[seeded]');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Mba Tifa' LIMIT 1),'Laptop','Asus','Win 11 Home','Digital License','Ryzen 5 7000','16 GB','512 GB','Office 2024 Home + 365','Baik','[seeded]');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Tito Sugiharta' LIMIT 1),'Laptop','Lenovo Yoga Slim 7','Win 11 Home','Digital License','Ultra 5 266V','16 GB','512 GB','Office 2024 Home','Baik','[seeded]');
INSERT INTO ac_assets(employee_id,device_type,brand,os,os_license_type,processor,ram,disk,office_version,condition,notes) VALUES((SELECT id FROM employees WHERE name='Annisa Hermaida' LIMIT 1),'Laptop','Asus','Win','OEM','Ryzen 5 7520U','16 GB','512 GB','Office 2024 Home','Baik','[seeded]');
INSERT INTO ac_asset_software(asset_id,software_name) VALUES(last_insert_rowid(),'Adobe Lightroom');

-- Infrastruktur
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Server','HP','ProLiant DL380 Gen9','host1.mmi-pt.com','','SH-MMI-01','UPS 01','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Server','Dell','PowerEdge R630','host2.mmi-pt.com','','SH-MMI-02','UPS 02','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Server','Dell','PowerEdge R630','host3.mmi-pt.com','','SH-MMI-03','UPS 03','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Server','HP','ProLiant DL320e Gen8 v2','host4.mmi-pt.com','','SH-MMI-04','UPS 04','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Server','Dell','PowerEdge R730','host5.mmi-pt.com','','SH-MMI-05','UPS 05','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Tools','','LAN Cable Tester','LAN Cable Tester','','ITS-MMI-LCT1.1','','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,status,condition_notes) VALUES('Tools','','LAN Cable Tester','','','ITS-MMI-LCT1.2','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Tools','','Tang Crimping','Tang Crimping','','ITS-MMI-TC','','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Router','Asus','Asus','Router','','ITS-MMI-RASUS','','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Access Point','TP-Link','TP-Link Access Point','AP TP-Link','','ITS-MMI-APTPL1','','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,status,condition_notes) VALUES('Access Point','TP-Link','TP-Link Access Point','','','ITS-MMI-APTPL2','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,status,condition_notes) VALUES('Access Point','TP-Link','TP-Link Access Point','','','ITS-MMI-APTPL3','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,status,condition_notes) VALUES('Access Point','TP-Link','TP-Link Access Point','','','ITS-MMI-APTPL4','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Switch','D-Link','D-Link Switch','Switch D-Link','','ITS-MMI-SDLINK','','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Router','Mikrotik','Routerboard Mikrotik 95U','Mikrotik 95U','','','','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Monitor','Philips','Monitor Philips HN57I50T','Philips','AU3A0745000557','ITS-MMI-M1','','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Peripheral','Logitech','Keyboard Logitech K210','Logitech','','ITS-MMI-KK1','','Aktif','[seeded]');
INSERT INTO ac_infrastructure(device_type,brand,model,description,serial_number,nickname,ups_group,status,condition_notes) VALUES('Peripheral','Logitech','Mouse Logitech B100','Logitech','','ITS-MMI-MK1','','Aktif','[seeded]');

-- Lisensi Software
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Timeline','UULQ-H3MK-1UQ4-CT1L-GLCF-KC9R-26HQ-75WZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Timeline','UULQ-H3MK-1UQ4-CT1L-GLCF-KC9R-26HQ-75WZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Project','M8GB2-NTQFX-R8XM7-6JVTF-F64PH','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Project','N328R-2JKKV-RG48X-GF67P-GRB2H','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Project','DGFTK-M3NG4-B7H6K-XH24R-DJ7F7','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_subscriptions(provider,category,billing_cycle,start_date,end_date,username,is_active,notes) VALUES('ChatGPT','SaaS','Monthly','2026-05-01','2026-06-01','admin@mmi-pt.com/K0song!naja',1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Project','J3P67-MNPWR-JQF44-326CD-C4BFB','Perpetual',2021,1,'[seeded]');
INSERT OR IGNORE INTO ac_subscriptions(provider,category,billing_cycle,start_date,end_date,username,is_active,notes) VALUES('Orbit','ISP','Monthly','2026-02-16','2026-03-16','donny@mitramandiri.co.id/P@ssw0rd',1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Project','K7NGF-QYWXM-4JY3P-4GFRK-8QQR7','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_subscriptions(provider,category,billing_cycle,start_date,end_date,username,is_active,notes) VALUES('MyRepublic IP Static','ISP','Monthly','2026-05-14','2026-06-14','itsupport@mmi-pt.com/otpcode',1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Project','XNKG7-JH824-K83FT-KXPTQ-4GHF7','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_subscriptions(provider,category,billing_cycle,start_date,end_date,username,is_active,notes) VALUES('Microsoft Teams Essentials','SaaS','Monthly','2026-05-11','2026-06-11','',1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Project','2QN6P-DXYCV-WGY8G-M9HX2-4RK47','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_subscriptions(provider,category,billing_cycle,start_date,end_date,username,is_active,notes) VALUES('Lightroom','SaaS','Yearly','2025-09-12','2026-09-11','annisa@mmi-pt.com/P@ssw0rd123!',1,'[seeded]');
INSERT OR IGNORE INTO ac_subscriptions(provider,category,billing_cycle,start_date,end_date,username,is_active,notes) VALUES('MyRepublic WIFI','ISP','Yearly','2025-09-15','2026-09-14','itsupport@mmi-pt.com/otpcode',1,'[seeded]');
INSERT OR IGNORE INTO ac_subscriptions(provider,category,billing_cycle,start_date,end_date,username,is_active,notes) VALUES('Office Timeline','SaaS','Yearly','2025-07-07','2026-07-07','david@mmi-pt.com/',1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Visio','BJKHR-NGXK2-XGKQD-CT6YX-4JWCX','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Visio','2B79W-HHNG7-3CFMY-9269H-464PX','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Visio','BYNBK-RPV3G-JD63P-7Q3RQ-9FB2X','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Visio','DCN9M-HFP47-4R3XY-3RPBT-PDQTK','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Visio','F4PQQ-JNKC3-6K77M-4RBTF-KBX6K','Perpetual',2024,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Visio','JXXFM-NR3TJ-GMTMG-Y4CHB-R637P','Perpetual',2021,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office 365','mmioffice3651@be10x.in','Subscription',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office 365','mmioffice3652@be10x.in','Subscription',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office 365','mmioffice3653@be10x.in','Subscription',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office 365','mmioffice3654@be10x.in','Subscription',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office 365','mmioffice3655@a.getcid.id','Subscription',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office 365','mmioffice3657@workspace365.pro','Subscription',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office 365','mmioffice3658@workspace365.pro','Subscription',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Pembelian yg Lama','mitramandiriinformatika@thunder.origin365.pro','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Pembelian yg Lama','mitramandiriinformatika1@thunder.origin365.pro','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Faststone','MMI_FastStone001 / GPYNK-JBEXT-RGSTS-NGGSE','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Faststone','MMI_FastStone002 / IPMNW-JTEBD-LNSYR-INFOL','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Faststone','MMI_FastStone003 / ZPAND-JJEDJ-INHON-WSQML','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Faststone','MMI_FastStone004 / UPSNY-JMEHB-QDLWE-VNDEZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Faststone','MMI_FastStone005 / TPTNE-JXEXP-NPZUO-RMCPP','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Faststone','MMI_FastStone006 / EPFNT-JWEUI-FSFWG-MNGMW','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Faststone','MMI_FastStone006 / EPFNT-JWEUI-FSFWG-MNGMW','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Windows 11 Pro','TND42-BTBVM-YVJ3H-FDMYT-PDKTT','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Windows 11 Pro','BCC4Q-NP9R7-YQPM2-B9W2X-7XMP6','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Windows 11 Pro','RYMTJ-HNQD7-QYKVH-DJWGD-TCQGY','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home 2024','232TV-VQJVG-CT73X-H9M7G-6QJQZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home 2024','9R7DD-JR76R-JXCJ3-7DMP7-JJDHZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home & Student 2021','2F9JM-DP9TW-K7673-Y7V3V-MP3QZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home & Student 2021','XDQ9J-RV6MW-PCTQ4-THYGM-XDFXZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home & Student 2021','PHRPV-Q7F66-WKYTR-R4P7P-V2PJZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home & Student 2021','VTRRK-MF3YT-D6WJF-Y4VH2-CRGCZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home & Student 2021','K43W6-WM79D-YWHHW-62QCM-XRQ4Z','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home & Student 2021','V6R3M-3VPW3-D4Y4V-KYFPF-Y4Y6Z','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home 2024','KRK3R-MJJPV-7VHG7-DQCFV-99J4Z','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home 2024','XWKM9-CKTC4-V7KH6-FDR6V-6DRYZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home 2024','MY4W6-3GHQW-GHC93-DYD4F-HVFRZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home 2024','WQW6K-WKK3K-43M6Y-9XF33-TX7QZ','Perpetual',NULL,1,'[seeded]');
INSERT OR IGNORE INTO ac_licenses(software_name,license_key,license_type,year,is_active,notes) VALUES('Office Home 2024','GG2FM-9WWWF-79PQQ-PPVG2-K3CTZ','Perpetual',NULL,1,'[seeded]');
