"""Seed data for all 5 divisions."""

# Ability items (shared across all divisions)
ABILITY_ITEMS = [
    ("Problem Decomposition",
     "Hanya menulis kode linier tanpa pemisahan masalah",
     "Mampu memecah masalah menjadi beberapa fungsi/prosedur",
     "Mampu membuat solusi yang dapat digunakan ulang (reusable)",
     "Menggunakan struktur data dan algoritma yang tepat"),
    ("Systems Decomposition",
     "Tidak mampu berpikir di atas level kode",
     "Mampu memecah masalah menjadi beberapa modul/komponen",
     "Mampu mendesain sistem yang mencakup banyak teknologi",
     "Mampu memvisualisasikan dan mendesain sistem yang kompleks"),
    ("Code/Work Organization",
     "Tidak ada tanda-tanda pengorganisasian pekerjaan",
     "Pekerjaan dikelompokkan secara logis dan terstruktur",
     "Pekerjaan dikelompokkan dalam bagian-bagian yang jelas",
     "Pekerjaan memiliki header, ringkasan, dan penjelasan yang lengkap"),
    ("Source Control / Document Management",
     "Semua pekerjaan dalam satu folder/tempat",
     "Pemisahan dasar antara kode/dokumen dan resource lain",
     "Tidak ada dependensi circular, pemisahan yang bersih",
     "Layout pekerjaan sesuai standar tim/perusahaan"),
    ("Readability",
     "Penamaan tidak deskriptif atau sulit dipahami",
     "Penamaan file, variabel, dan fungsi sudah baik",
     "Tidak ada fungsi/proses yang terlalu panjang, komentar menjelaskan dengan baik",
     "Asumsi kode sudah diverifikasi, sangat mudah dibaca"),
    ("Defensive Working",
     "Tidak memahami konsep validasi/error prevention",
     "Memeriksa semua argumen dan input yang relevan",
     "Memastikan nilai kembalian dicek sebelum digunakan",
     "Memiliki library/metode sendiri untuk membantu validasi"),
    ("Error Handling",
     "Hanya menangani kasus normal (happy path)",
     "Penanganan error dasar di sekitar kode kritis",
     "Memastikan error/exception ditangani dengan benar",
     "Menulis kode untuk mendeteksi kemungkinan exception sebelum terjadi"),
    ("Tool Usage (IDE/Apps)",
     "Hanya menggunakan tools utama untuk pengeditan teks",
     "Mengenal fitur-fitur penting dari tools yang digunakan",
     "Mengetahui shortcut keyboard untuk operasi umum",
     "Telah membuat custom macro/plugin/automation untuk tools"),
    ("API / Documentation",
     "Perlu mencari dokumentasi untuk semua hal",
     "Menguasai API/dokumentasi yang paling sering digunakan",
     "Pengetahuan luas dan mendalam tentang product/sistem",
     "Telah menulis library/modul yang melapisi API utama"),
    ("Framework / Process Knowledge",
     "Belum pernah menggunakan framework atau metodologi formal",
     "Pernah mendengar tapi belum menggunakan lebih dari satu",
     "Telah menggunakan lebih dari satu framework/metodologi",
     "Penulis/kontributor framework atau metodologi yang digunakan"),
    ("Requirements Understanding",
     "Mengerjakan requirement apa adanya tanpa analisis",
     "Mengajukan pertanyaan untuk memperjelas requirement",
     "Memahami gambaran besar dan dampak dari requirement",
     "Mampu menyarankan alternatif yang lebih baik"),
    ("Scripting / Automation",
     "Tidak mengetahui tools scripting/otomasi",
     "Menggunakan batch file / shell script dasar",
     "Perl/Python/Ruby/PowerShell/VBScript",
     "Telah menulis dan mempublikasikan tools reusable"),
    ("Database Knowledge",
     "Hanya mengandalkan spreadsheet / tidak mengerti database",
     "Mengenal konsep database dasar, mampu menulis query sederhana",
     "Mampu mendesain database yang dinormalisasi dengan baik",
     "Mampu melakukan administrasi database dasar dan optimasi query"),
    ("Domain Knowledge",
     "Tidak mengetahui domain bisnis yang dikerjakan",
     "Pernah mengerjakan minimal satu proyek di domain ini",
     "Pernah mengerjakan multiple produk di domain ini",
     "Expert di domain ini, mampu mendesain dan mengembangkan produk baru"),
    ("Tool & Technology Awareness",
     "Hanya terbatas pada tools utama yang saat ini digunakan",
     "Mengetahui beberapa alternatif tools yang tersedia",
     "Pengetahuan baik tentang berbagai tools dan teknologi",
     "Telah mengembangkan tools sendiri dan berkontribusi ke komunitas"),
    ("Knowledge of Upcoming Technologies",
     "Tidak pernah mendengar tentang teknologi terbaru",
     "Pernah mendengar tentang teknologi yang akan datang",
     "Telah mengunduh/mencoba preview teknologi baru",
     "Aktif bermain dengan preview dan berkontribusi ke komunitas"),
    ("Platform Internals",
     "Tidak memiliki pengetahuan tentang platform internal",
     "Memiliki pengetahuan dasar tentang cara kerja platform",
     "Pengetahuan mendalam tentang platform yang digunakan",
     "Telah membuat tools untuk meningkatkan platform"),
    ("Knowledge Sharing",
     "Pernah mendengar tapi tidak pernah berbagi pengetahuan",
     "Membaca tech/programming blog, sesekali berbagi ke tim",
     "Secara rutin berbagi link/artikel dengan tim, membuat dokumentasi",
     "Mempertahankan blog/wiki aktif, menjadi narasumber internal"),
]

# =================== PROGRAMMER ===================
PROGRAMMER_SKILL_CATS = [
    ("General", [
        ("SDLC", "Pemahaman terhadap SDLC beserta implementasinya", 4),
        ("MVC", "Pemahaman terhadap MVC beserta implementasinya", 4),
        ("OOP", "Pemahaman terhadap OOP beserta implementasinya", 4),
        ("Source Control Management", "", 3),
        ("SOAP", "Memahami konsep SOAP, produce, consume", 1),
        ("Restful/API", "", 4),
        ("Transaction Management", "", 4),
        ("Asynchronous & Synchronous", "", 4),
        ("Socket & Websocket Programming", "", 2),
        ("Stress Test", "", 2),
        ("Penetration Test", "", 3),
        ("Automation Test", "", 1),
        ("Unit Test (JUnit)", "", 2),
        ("SSO", "", 2),
        ("Microservice", "Pemahaman dan pengalaman dalam pengembangan microservice", 4),
        ("Modular Programming", "Pemahaman dan pengalaman dalam modular programming", 4),
        ("Application Security", "Pemahaman dan pengalaman dalam application security", 3),
        ("Application Performance Optimization", "Pemahaman dan pengalaman optimasi performa aplikasi", 3),
        ("CI/CD", "Continuous Integration dan Continuous Deployment", 2),
        ("Arsitektur Aplikasi dan Desain", "Pemahaman dan pengalaman pengembangan aplikasi", 2),
        ("Threading Programming", "Pemahaman Thread dan pengalaman penggunaannya", 2),
    ]),
    ("Product Knowledge", [
        ("Bispro VM", "Pemahaman mengenai bisnis proses Vendor Management", 3),
        ("Bispro PM", "Pemahaman mengenai bisnis proses Procurement Management", 3),
        ("Bispro CM", "Pemahaman mengenai bisnis proses Contract Management", 3),
        ("Bispro ESM", "Pemahaman mengenai bisnis proses ESM", 3),
        ("Product versi 1 & 2", "Pemahaman mengenai Product Promise versi 1 & 2", 4),
        ("Product versi 3", "Pemahaman mengenai Product Promise versi 3", 4),
        ("Product versi 4", "Pemahaman mengenai Product Promise versi 4", 4),
        ("Proman architecture & design", "Pemahaman mengenai Arsitektur Promise & Design", 3),
        ("Procurite architecture & design", "Pemahaman mengenai Arsitektur Procurite & Design", 0),
    ]),
    ("Java", [
        ("Java OOP", "", 4),
        ("GraalVM", "", 1),
        ("JVM", "", 2),
        ("Standard Naming Convention", "", 2),
        ("Springboot Framework", "", 4),
        ("Quarkus Framework", "", 0),
        ("Java Native Image", "", 0),
        ("Generics in Java", "", 2),
        ("JDBC", "", 4),
        ("Entity Graph", "", 4),
        ("Java Annotation", "", 4),
        ("Maven", "", 4),
        ("JSP / JSTL", "", 4),
        ("JPA", "", 4),
    ]),
    ("UI / Javascript / HTML", [
        ("Javascript", "", 4),
        ("Typescript", "", 4),
        ("jQuery", "", 3),
        ("HTML", "", 4),
        ("Bootstrap", "", 2),
        ("CSS, SCSS", "", 2),
        ("Browser Debug", "", 4),
        ("Cookies", "", 1),
    ]),
    ("Server / Webserver", [
        ("JBoss", "", 3),
        ("Tomcat", "", 3),
        ("Linux Shell", "", 4),
        ("Shell Scripting", "", 4),
        ("Nginx / Reverse Proxy", "", 2),
    ]),
    ("Database", [
        ("MySQL", "", 4),
        ("SQL Server", "", 4),
        ("PostgreSQL", "", 4),
        ("Oracle", "", 4),
        ("MongoDB", "", 4),
        ("Redis", "", 4),
        ("SQL Database Indexing", "", 4),
        ("SQL Store Procedure & Function", "", 4),
        ("SQL Database Trigger", "", 4),
        ("SQL Query", "", 4),
        ("NoSQL Query", "", 4),
    ]),
    ("Tools / Framework / Library", [
        ("Eclipse", "", 2),
        ("Visual Studio Code", "", 4),
        ("Docker", "", 4),
        ("Kubernetes", "", 3),
        ("Keycloak", "", 3),
        ("Grafana", "", 0),
        ("RabbitMQ", "", 3),
        ("Onlyoffice", "", 1),
        ("Jenkins", "", 2),
        ("Nexus", "", 1),
        ("SonarQube", "", 4),
        ("Apache POI", "", 4),
        ("Apache Kafka", "", 3),
        ("Apache CXF", "", 1),
        ("Gradle", "", 1),
        ("Jasper Report", "", 4),
        ("Openshift", "", 3),
        ("Dynamic Jasper", "", 1),
        ("Spring Boot", "", 4),
        ("Angular", "", 4),
        ("Prometheus", "", 1),
        ("ReactJS", "", 4),
        ("Node.js", "", 4),
        ("NPM", "", 4),
        ("JMeter", "", 3),
        ("K6", "", 3),
        ("MinIO", "", 0),
    ]),
]

PROGRAMMER_COMPETENCY = [
    ("Penyelesaian task sesuai mandate/sprint", 0.11, 0),
    ("Mitigasi risiko keterlambatan task", 0.08, 0),
    ("Update progress mingguan", 0.06, 0),
    ("Task sesuai FSD/TSD", 0.11, 0),
    ("UI Testing sesuai skenario", 0.08, 0),
    ("Penilaian project saat PIR", 0.11, 0),
    ("Pelatihan dan knowledge sharing", 0.06, 0),
    ("Penerapan teknologi baru / reuse code", 0.06, 0),
    ("Menjadi project lead", 0.08, 0),
    ("Kolaborasi dan awareness", 0.04, 0),
    ("Dokumentasi kode", 0.06, 0),
    ("Hard Skill", 0.15, 1),  # is_hardskill=1
]

# =================== IMPLEMENTOR/BPS ===================
IMPLEMENTOR_SKILL_CATS = [
    ("General", [
        ("SDLC", "Pemahaman terhadap SDLC beserta implementasinya", 4),
        ("Source Control Management", "", 2),
        ("Restful/API", "Mampu consume/test API", 3),
        ("Database Query", "Mampu menulis query SQL dasar hingga menengah", 3),
        ("Application Security Basics", "Pemahaman dasar keamanan aplikasi", 2),
        ("Documentation (FSD/TSD/UAT)", "Mampu membaca dan membuat dokumen teknis", 4),
        ("Linux Shell Basics", "Penggunaan dasar Linux shell", 3),
    ]),
    ("Product Knowledge", [
        ("Bispro VM", "Pemahaman bisnis proses Vendor Management", 3),
        ("Bispro PM", "Pemahaman bisnis proses Procurement Management", 3),
        ("Bispro CM", "Pemahaman bisnis proses Contract Management", 3),
        ("Bispro ESM", "Pemahaman bisnis proses ESM", 3),
        ("Product versi 1 & 2", "", 4),
        ("Product versi 3", "", 4),
        ("Product versi 4", "", 4),
        ("Product Architecture Overview", "Pemahaman arsitektur produk secara umum", 3),
    ]),
    ("Implementation", [
        ("Environment Setup (Linux/Windows)", "Menyiapkan environment untuk deployment", 4),
        ("Application Deployment", "Melakukan deployment aplikasi ke server", 4),
        ("Configuration Management", "Mengelola konfigurasi aplikasi (properties/env)", 3),
        ("Data Migration", "Melakukan migrasi data antar sistem/versi", 3),
        ("SSL / Certificate Setup", "Konfigurasi SSL dan certificate", 2),
        ("Load Balancer Configuration", "Konfigurasi load balancer dasar", 2),
        ("Rollback Procedure", "Prosedur rollback saat deployment gagal", 3),
    ]),
    ("Tools", [
        ("Visual Studio Code / Eclipse", "", 3),
        ("Docker", "", 3),
        ("Nginx / Apache", "", 3),
        ("Jira / Redmine", "Manajemen tiket implementasi", 4),
        ("Postman / REST Client", "Testing API endpoint", 3),
        ("SQL Client (DBeaver/HeidiSQL)", "", 3),
        ("Remote Access (SSH/RDP)", "", 4),
        ("Jenkins / CI Basic", "", 2),
    ]),
]

IMPLEMENTOR_COMPETENCY = [
    ("Penyelesaian implementasi sesuai jadwal", 0.12, 0),
    ("Dokumentasi implementasi dan UAT", 0.10, 0),
    ("Komunikasi dan koordinasi dengan klien", 0.10, 0),
    ("Mitigasi risiko implementasi", 0.08, 0),
    ("Training user di sisi klien", 0.10, 0),
    ("Update progress implementasi mingguan", 0.06, 0),
    ("Penanganan issue saat go-live", 0.12, 0),
    ("Kolaborasi dengan tim development", 0.08, 0),
    ("Laporan pasca implementasi", 0.06, 0),
    ("Kolaborasi dan awareness", 0.04, 0),
    ("Penguasaan product yang diimplementasikan", 0.05, 0),
    ("Hard Skill", 0.09, 1),
]

# =================== HELPDESK SUPPORT ===================
HELPDESK_SKILL_CATS = [
    ("General", [
        ("SDLC Basics", "Pemahaman dasar SDLC", 2),
        ("Problem Analysis & Troubleshooting", "Kemampuan analisis dan pemecahan masalah", 4),
        ("Documentation & Reporting", "Membuat dokumentasi solusi dan laporan", 3),
        ("Communication Skills", "Komunikasi tertulis dan verbal yang efektif", 4),
        ("Escalation Management", "Mengetahui kapan dan bagaimana melakukan eskalasi", 3),
        ("SLA Awareness", "Pemahaman tentang SLA dan prioritas tiket", 4),
    ]),
    ("Product Knowledge", [
        ("Bispro VM", "Pemahaman bisnis proses Vendor Management", 4),
        ("Bispro PM", "Pemahaman bisnis proses Procurement Management", 4),
        ("Bispro CM", "Pemahaman bisnis proses Contract Management", 3),
        ("Bispro ESM", "Pemahaman bisnis proses ESM", 3),
        ("Product versi 1 & 2", "", 4),
        ("Product versi 3", "", 4),
        ("Product versi 4", "", 4),
        ("FAQ & Known Issues", "Penguasaan FAQ dan known issues produk", 4),
    ]),
    ("Support Tools", [
        ("Helpdesk / Ticketing System (JIRA/Redmine)", "", 4),
        ("Remote Desktop / TeamViewer / AnyDesk", "", 4),
        ("Email Management & Etiquette", "", 4),
        ("Screen Recording & Capture Tools", "", 3),
        ("Knowledge Base Management", "", 3),
        ("Live Chat Tools", "", 3),
    ]),
    ("Technical Basics", [
        ("Database Query (SELECT dasar)", "", 2),
        ("Log Reading & Analysis", "Membaca dan menganalisis log aplikasi", 3),
        ("Browser Dev Tools", "Menggunakan developer tools browser", 2),
        ("Network Basics (TCP/IP, DNS)", "", 2),
        ("VPN Usage", "", 3),
        ("OS Basics (Windows/Linux)", "", 3),
    ]),
]

HELPDESK_COMPETENCY = [
    ("Response time terhadap tiket/laporan", 0.15, 0),
    ("First call resolution / solusi tepat", 0.12, 0),
    ("Kepuasan user (CSAT)", 0.10, 0),
    ("Dokumentasi solusi dan knowledge base", 0.08, 0),
    ("Eskalasi tiket yang tepat dan tepat waktu", 0.10, 0),
    ("Update status tiket secara rutin", 0.08, 0),
    ("Penguasaan product yang disupport", 0.08, 0),
    ("Komunikasi dan etika pelayanan", 0.08, 0),
    ("Kolaborasi dan awareness", 0.06, 0),
    ("Pelatihan dan knowledge sharing", 0.05, 0),
    ("Hard Skill", 0.10, 1),
]

# =================== TESTER ===================
TESTER_SKILL_CATS = [
    ("General", [
        ("SDLC & STLC", "Pemahaman Software Testing Life Cycle", 4),
        ("Black Box Testing", "Pengujian fungsional tanpa melihat source code", 4),
        ("White Box Testing", "Pengujian dengan melihat source code", 2),
        ("Regression Testing", "Pengujian regresi setelah perubahan", 4),
        ("Performance Testing", "Pengujian performa/beban aplikasi", 2),
        ("Security Testing", "Pengujian keamanan aplikasi dasar", 2),
        ("API Testing", "Pengujian endpoint API", 3),
        ("Mobile Testing", "Pengujian aplikasi mobile", 2),
        ("Database Testing", "Verifikasi data di database", 3),
        ("Usability Testing", "Pengujian kemudahan penggunaan UI/UX", 3),
    ]),
    ("Product Knowledge", [
        ("Bispro VM", "Pemahaman bisnis proses Vendor Management", 4),
        ("Bispro PM", "Pemahaman bisnis proses Procurement Management", 4),
        ("Bispro CM", "Pemahaman bisnis proses Contract Management", 4),
        ("Bispro ESM", "Pemahaman bisnis proses ESM", 3),
        ("Product versi 1 & 2", "", 4),
        ("Product versi 3", "", 4),
        ("Product versi 4", "", 4),
        ("FSD/TSD Reading & Analysis", "Mampu membaca dan menganalisis FSD/TSD", 4),
    ]),
    ("Test Tools", [
        ("Selenium / WebDriver", "", 3),
        ("JMeter", "Performance testing", 3),
        ("K6", "Load testing modern", 2),
        ("Postman / REST Client", "API testing", 4),
        ("TestNG / JUnit", "", 3),
        ("SonarQube", "Code quality analysis", 2),
        ("JIRA / Bugzilla", "Bug tracking", 4),
        ("Browser Dev Tools", "", 4),
        ("SQL Client", "Database verification", 3),
        ("Appium", "Mobile testing automation", 1),
    ]),
    ("Documentation", [
        ("Test Plan", "Membuat rencana pengujian", 4),
        ("Test Case", "Membuat skenario dan test case", 4),
        ("Bug Report", "Membuat laporan bug yang detail dan akurat", 4),
        ("Test Summary Report", "Membuat laporan hasil pengujian", 3),
        ("UAT Documentation", "Dokumentasi user acceptance testing", 3),
        ("Test Matrix / Traceability Matrix", "", 2),
    ]),
]

TESTER_COMPETENCY = [
    ("Test coverage sesuai skenario/TSD", 0.12, 0),
    ("Pelaporan bug yang akurat dan detail", 0.12, 0),
    ("Pembuatan dan maintenance test case", 0.10, 0),
    ("Regression testing", 0.10, 0),
    ("Update progress testing mingguan", 0.06, 0),
    ("Koordinasi dengan developer untuk bug fixing", 0.08, 0),
    ("Dokumentasi hasil testing", 0.10, 0),
    ("Penilaian kualitas produk saat PIR", 0.08, 0),
    ("Penerapan metode/tools testing baru", 0.06, 0),
    ("Kolaborasi dan awareness", 0.04, 0),
    ("Ketepatan UAT sign-off", 0.04, 0),
    ("Hard Skill", 0.10, 1),
]

# =================== IT SUPPORT ===================
IT_SUPPORT_SKILL_CATS = [
    ("General", [
        ("Network Architecture", "Pemahaman arsitektur jaringan enterprise", 3),
        ("Security Principles", "Prinsip-prinsip keamanan IT", 3),
        ("ITIL / Service Management", "Pemahaman ITIL framework", 2),
        ("Monitoring Concepts", "Konsep monitoring sistem dan aplikasi", 3),
        ("Documentation", "Dokumentasi infrastruktur dan prosedur", 3),
        ("Shell Scripting (Bash/PowerShell)", "", 3),
        ("Ticketing System", "", 4),
    ]),
    ("Network & Infrastructure", [
        ("TCP/IP", "", 4),
        ("DNS / DHCP", "", 4),
        ("Firewall Configuration", "", 3),
        ("VPN Setup & Management", "", 3),
        ("Load Balancer", "", 2),
        ("Network Monitoring (Zabbix/Nagios)", "", 3),
        ("Routing & Switching Basics", "", 2),
        ("WiFi Management", "", 2),
    ]),
    ("Server Management", [
        ("Linux Administration", "", 4),
        ("Windows Server", "", 3),
        ("Docker / Containerization", "", 3),
        ("Kubernetes Basics", "", 2),
        ("VM Management (VMware/KVM)", "", 3),
        ("Backup & Recovery", "", 4),
        ("Log Management (ELK/Graylog)", "", 3),
        ("Cron & Task Automation", "", 3),
    ]),
    ("Security", [
        ("Vulnerability Assessment", "", 2),
        ("SSL/TLS Certificate Management", "", 3),
        ("Active Directory / LDAP", "", 2),
        ("Intrusion Detection Basics", "", 2),
        ("Patch Management", "", 3),
        ("Security Audit", "", 2),
    ]),
    ("Monitoring & Tools", [
        ("Grafana", "", 3),
        ("Prometheus", "", 2),
        ("Zabbix / Nagios", "", 2),
        ("ELK Stack", "", 2),
        ("APM (Application Performance Monitoring)", "", 2),
        ("Alerting & Notification", "", 3),
    ]),
]

IT_SUPPORT_COMPETENCY = [
    ("Uptime infrastruktur sesuai SLA", 0.15, 0),
    ("Incident response time", 0.12, 0),
    ("Implementasi keamanan sistem", 0.10, 0),
    ("Dokumentasi infrastruktur", 0.08, 0),
    ("Monitoring dan alerting proaktif", 0.10, 0),
    ("Update, patching, dan backup rutin", 0.08, 0),
    ("Penanganan user/developer request", 0.08, 0),
    ("Kolaborasi dengan tim development", 0.07, 0),
    ("Pelatihan dan knowledge sharing", 0.05, 0),
    ("Kolaborasi dan awareness", 0.05, 0),
    ("Hard Skill", 0.12, 1),
]

ALL_DIVISIONS = {
    "Programmer":       (PROGRAMMER_SKILL_CATS,  PROGRAMMER_COMPETENCY),
    "Implementor/BPS":  (IMPLEMENTOR_SKILL_CATS, IMPLEMENTOR_COMPETENCY),
    "Helpdesk Support": (HELPDESK_SKILL_CATS,    HELPDESK_COMPETENCY),
    "Tester":           (TESTER_SKILL_CATS,       TESTER_COMPETENCY),
    "IT Support":       (IT_SUPPORT_SKILL_CATS,  IT_SUPPORT_COMPETENCY),
}
