sonar.projectKey=hive-prod
sonar.projectName=hive-prod

sonar.login=sqa_41f5251a3264187ae3fcb676dd573a780b045715
sonar.host.url=http://10.150.10.61:9000/

# Pengaturan Encoding dan Path Source Code
sonar.sourceEncoding=UTF-8
sonar.sources=.

# Mengecualikan folder/file yang tidak perlu dianalisis (seperti tes, environment, cache, dll)
sonar.exclusions=tests/**, __pycache__/**, venv/**, .venv/**, env/**, .pytest_cache/**, static/**, *.db, *.pyc, fetch_sonar_issues.py

# Mengaktifkan Code Coverage untuk Python
sonar.python.coverage.reportPaths=coverage.xml

# Menentukan bahasa pemrograman (Python)
sonar.language=py

# Pengaturan Path untuk Unit Test (Jika ada)
sonar.tests=tests
sonar.test.inclusions=tests/**

# Path report coverage jika Anda menggenerate XML coverage via pytest-cov di Jenkins
# sonar.python.coverage.reportPaths=coverage.xml

# SCM configuration
sonar.scm.disabled=True
