VERSION = "2.2.73"
RELEASE_DATE = "2026-07-11"
RELEASE_NOTES = (
    "v2.2.73: Menambahkan log diagnostik dan penanganan exception pada fungsi reply di Telegram webhook untuk mempermudah pelacakan pengiriman pesan. "
    "v2.2.72: Menyertakan ID group Telegram ke dalam catatan lokasi/notes attendance, memperbaiki bug NameError 'user_mention' pada respon start/help/absen, dan menampilkan detail ID grup pada balasan command di grup yang sama. "
    "v2.2.71: Perbaikan role saving agar app-scoped (tidak menimpa app lain) dan penambahan default at_view/at_manage ke sistem role defaults saat startup/seeding. "
    "v2.2.70: Fix at_require helper in AttendanceCore to check permissions via get_db() has_permission instead of unpopulated session['user_permissions']. "
    "v2.2.69: Perubahan mass add akses menggunakan data karyawan (auto-create user account dengan key email dan default password hive2026, sso untuk @mmi-pt.com, login support username/email). "
    "v2.2.68: Hapus checkbox legacy permission di portal_roles (diganti auto-derive) dan tambah fitur mass add akses aplikasi di portal_settings. "
    "v2.2.67: Fix issue UndefinedColumn/UniqueViolation pada PostgreSQL saat penyimpanan menu role di portal_roles. "
    "v2.2.66: Pembenahan sistem Role & Permission menggunakan menu dan child menu dinamis dari database serta antarmuka Drag n Drop di Portal. "
    "v2.2.0: Objektifikasi penilaian — difficulty task, self_assigned flag, "
    "peer review 5 dimensi, benchmark per grade, AI summary (Ollama), "
    "dashboard Performa Divisi dengan peak/low/overload detection. "
    "v2.2.1: Panel Analisa Sistem di Review Evaluasi; export Excel/PDF; "
    "hapus tombol Lihat Gaji dari tabel karyawan. "
    "v2.2.2: Auto-fill Project Performance dari ProjectCore/SupportCore/POC; "
    "Ability AI Suggest berbasis data sistem (task score, difficulty, customer, POC); "
    "fix Hard Skill error 500 (ROUND::numeric PostgreSQL); "
    "fix evaluasi review_status draft → self_filled/approved; "
    "fix period_start → task_date_from di eval_review route. "
    "v2.2.3: Global error handler 500 → audit_errors; /admin/error-log page; "
    "fix due_date::date cast, self_assigned=1, pc_projects done_issues subquery. "
    "v2.2.4: Autofill Project — status proyek mapped ke DONE/ONPROGRESS/CANCELLED; "
    "Top Task: ranked list per project+customer by task/tiket count; "
    "Improvement: satu baris per POC/presales + 2 baris manual input kosong. "
    "v2.2.5: Perbaikan bug pencarian query cari_aset pada AI Chatbot agar mendukung kolom database yang valid. "
    "v2.2.6: Memperbaiki error NoneType not subscriptable pada halaman profil jika user dihapus or tidak aktif. "
    "v2.2.7: Menambahkan opsi --reset-superadmin pada script deploy-ubuntu.sh untuk melakukan reset password superadmin. "
    "v2.2.8: Memperbaiki pemuatan variabel lingkungan (.env) saat menjalankan reset password superadmin. "
    "v2.2.9: Memperbaiki SyntaxError di PostgreSQL pada halaman Infrastruktur Aset dan Lisensi Aset akibat tanda kutip ganda. "
    "v2.2.10: Menghapus menu dan rute error log yang redundan di TalentCore (digantikan oleh Audit Trail Portal). "
    "v2.2.11: Mengubah HelpdeskCore menjadi AttendanceCore dengan fitur live attendance, leave, overtime, dan correction. "
    "v2.2.12: Menambahkan integrasi Telegram Bot untuk melakukan absensi (Clock In / Clock Out) dengan mengirimkan lokasi (Send Location). "
    "v2.2.13: Peningkatan ketahanan Webhook Telegram (case-insensitive username, edited_message) and integrasi perbaikan/error-handling pencatatan lokasi di Web UI. "
    "v2.2.14: Memperbaiki pencocokan identitas user Telegram di Webhook saat mengirim lokasi di dalam grup dengan memetakan user.id (sender) alih-alih chat.id (group ID). "
    "v2.2.15: Mewajibkan strict Geolocation GPS pada Clock In dan Clock Out Web Attendance Core (tanialah koordinat kosong) and menghapus input catatan. "
    "v2.2.16: Integrasi PLAN and PROGRESS dari Telegram Bot ke modul Presensi Harian (AttendanceCore) dengan tampilan UI detail modal. "
    "v2.2.17: Menghapus secara permanen record registrasi aplikasi obsolete (HelpdeskCore) dari database superapp_apps saat inisialisasi aplikasi. "
    "v2.2.18: Memperbaiki konversi datetime SQLite ke PostgreSQL untuk query AssetCore and penanganan duplicate username agar kompatibel dengan psycopg2. "
    "v2.2.19: Menambahkan modul Backup Center di Portal untuk backup source code aplikasi, konten uploads, dan database dengan pengiriman email, upload S3, download langsung, dan scheduler. "
    "v2.2.20: Memperbaiki kegagalan manual backup PostgreSQL akibat program pg_dump tidak ditemukan dengan menambahkan dependency postgresql-client dan dukungan kustom PG_DUMP_PATH. "
    "v2.2.21: Memperbaiki bug status backup yang tidak terupdate ('Belum Pernah Run') di PostgreSQL karena transaction rollback akibat kegagalan query dengan RETURNING id pada tabel app_settings. "
    "v2.2.22: Menambahkan manual loader untuk berkas .env pada inisialisasi awal app.py agar DB_TYPE terdeteksi sesuai (PostgreSQL) serta menambahkan prefix folder backups/ pada upload S3. "
    "v2.2.23: Implementasi script backup_db.sh terpisah untuk backup PostgreSQL dengan credential env/admin, fitur hapus backup langsung, dan batas retensi housekeeping lokal. "
    "v2.2.24: Menambahkan perbaikan environment PATH di evaluasi.service and script backup_db.sh untuk mengatasi error command not found (dirname, grep, xargs, pg_dump). "
    "v2.2.25: Mengaktifkan default auto backup lokal & S3 di DEFAULT_SETTINGS, serta mendukung opsi penyimpanan konten media (static/uploads) ke S3 (folder upload/media/). "
    "v2.2.26: Memperbaiki bug 0-byte image upload akibat stream consumption dan timeout/Gunicorn restart saat S3 enabled tapi credentials kosong/koneksi lambat. "
    "v2.2.27: Implementasi rute media proxy (/media/proxy/<path:key>) untuk mengamankan data S3 tetap private dengan streaming file media secara terotentikasi. "
    "v2.2.28: Memindahkan rute media_proxy ke posisi setelah definisi login_required di app.py untuk mengatasi NameError saat boot. "
    "v2.2.29: Memperbaiki bug nested forms pada template edit resource BookingCore, mengaktifkan AJAX image deletion, dan mendukung multi-upload gallery saat menambahkan resource. "
    "v2.2.30: Memperbaiki TemplateSyntaxError (stray endif tag) di booking_resource_edit.html setelah pembersihan nested forms. "
    "v2.2.31: Menambahkan tampilan dashboard BookingCore berformat kalender bulanan lengkap dengan detail jadwal resources dan pemesan. "
    "v2.2.32: Sinkronisasi kalender bulanan BookingCore dengan libur nasional Indonesia dan cuti bersama menggunakan REST API. "
    "v2.2.33: Mengubah informasi booking di dalam kalender bulanan BookingCore agar menampilkan nama Resource, Jam Booking, dan Pemesan. "
    "v2.2.34: Memperbaiki bug input is_active yang terlewat saat proses penambahan resource baru di BookingCore. "
    "v2.2.35: Implementasi Media Library Selector untuk memilih media terunggah (local/S3), folder penyimpanan bookingcore khusus, dan fitur hapus resource secara permanen. "
    "v2.2.36: Implementasi Public Booking Dashboard (/booking/public) tanpa otentikasi login, dengan visualisasi TV Monitor modern, live clock, auto-refresh, dan S3 media public bypass untuk file resource. "
    "v2.2.37: Memperbaiki error UndefinedColumn start_time/end_time di PostgreSQL dengan mengubahnya ke start_dt/end_dt, dan menyertakan JOIN JOIN users untuk memuat nama pemesan. "
    "v2.2.38: Menambahkan kategori sidebar 'Lainnya' untuk menampilkan equipment (Proyektor Portable), dan memperkuat visual/kontras TV display agar lebih enterprise-grade. "
    "v2.2.39: Implementasi fitur Request Alat Kerja (Laptop) di AssetCore dengan input admin PIC untuk tipe, spesifikasi, link pembelian online, dan estimasi harga. "
    "v2.2.40: Perluasan form Request Alat Kerja sesuai format pembelian laptop, spek opsional CPU/RAM/disk, dan auto-create asset Laptop/PC saat request Completed dengan kompatibilitas PostgreSQL. "
    "v2.2.41: Menambahkan requested-by channel pada Request Alat Kerja serta multi attachment untuk capture request dan foto unit pembelian/checking. "
    "v2.2.42: Memperbaiki otorisasi AssetCore (dan core lainnya) agar mendeteksi role spesifik aplikasi (app_role dari user_app_access) dan menggabungkannya ke user_perms. "
    "v2.2.43: Mengunci request alat kerja yang Completed (greyed out & disabled) serta menghubungkan detail asset & list asset dengan info request alat kerja asal. "
    "v2.2.44: Menambahkan requestor name, mengubah label Tanggal Masuk menjadi Tanggal Proses IT Support, serta implementasi master hardware specs/software dengan combo datalist. "
    "v2.2.45: Redesain halaman Laporan & Analitik SupportCore dengan visualisasi modern ala Meridian (KPI Cards dan interactive charts dengan ApexCharts). "
    "v2.2.46: Memperbaiki ValueError tool_request_id is not in list pada daftar asset dengan menambahkan query tool_request_id di route ac_assets. "
    "v2.2.47: Memperbaiki ValueError loop unpacking too many values to unpack (expected 2) pada data serialisasi templates/sc_reports.html. "
    "v2.2.48: Peningkatan dan redesain layout/tema HIVE secara global ke gaya Meridian (Stisla V3) menggunakan font Inter, light-sidebar premium dengan aksen ungu, serta card & input modern. "
    "v2.2.49: Menambahkan toggle minimize/maximize sidebar menu pada tampilan desktop menggunakan HTML5 localStorage persistence. "
    "v2.2.50: Menyembunyikan seluruh teks link menu sidebar saat diminimize (menampilkan ikon saja), menghapus user dropdown dari sidebar, dan menyatukannya ke dropdown user di header atas. "
    "v2.2.51: Menambahkan validasi wajib upload bukti attachment (capture approval/rejection) saat status Request Alat Kerja dirubah ke Approved atau Rejected, baik di sisi client (browser) maupun server. "
    "v2.2.52: Menambahkan validasi wajib upload bukti serah terima perangkat (BAST/foto) saat status Request Alat Kerja dirubah ke Completed, baik di sisi client maupun server. "
    "v2.2.53: Memperbaiki error read timed out pada notifikasi Telegram AssetCore dengan mengurangi timeout dari 10s ke 5s dan mengirim notifikasi fire-and-forget secara non-blocking di background thread. "
    "v2.2.54: Menambahkan tombol manual trigger form review evaluasi karyawan di halaman Manajemen Karyawan (kontrak & tetap), dengan modal konfirmasi periode dan pengiriman link self-assessment otomatis via email/Telegram. "
    "v2.2.55: Menyempurnakan Telegram Webhook AttendanceCore agar mendukung group/private chat location tagging, validasi minimal 10 karakter untuk #PLAN dan #PROGRESS (bersih dari tag), dan memblokir Clock Out sampai plan & progress lengkap. "
    "v2.2.56: Memperbaiki deteksi user Telegram dengan mengecek tabel users dan employees, serta memindahkan respons bot ke Telegram agar dikirim terlebih dahulu sebelum proses tulis database (commit). "
    "v2.2.57: Menghapus total dukungan database SQLite dan mematikan fallback local database SQLite, memaksa penggunaan database PostgreSQL secara penuh (global default)."
    "v2.2.58: Menambahkan dukungan kompatibilitas terhadap custom JSON payload yang dikirimkan oleh Node.js helper bot (Telegraf location forwarder)."
    "v2.2.59: Menambahkan tabel Status Kehadiran Karyawan Hari Ini (Live Attendance Wall) pada dashboard AttendanceCore untuk menampilkan informasi clock-in, clock-out, lokasi, plan, dan progress seluruh karyawan."
    "v2.2.60: Pengetatan alur presensi Telegram: Rencana kerja (#PLAN) tidak dapat diisi sebelum Clock In, laporan kemajuan (#PROGRESS) tidak dapat diisi sebelum #PLAN lengkap, dan Clock Out diblokir hingga keduanya diisi secara terpisah."
    "v2.2.61: Menambahkan informasi nama Telegram Group pengirim absensi serta kolom kalkulasi Durasi Kerja (jam) hasil selisih Clock Out dan Clock In pada tabel Live Attendance Wall."
    "v2.2.62: Memperbaiki prioritas deteksi Telegram ID ke tabel karyawan (employees) terlebih dahulu, menambahkan auto-register fallback untuk pengguna tidak dikenal, mendukung clock-out berulang (update checkout), dan menambahkan detail nama grup pada balasan bot Telegram."
    "v2.2.63: Pemutakhiran menyeluruh dokumen repositori (README.md, BLUEPRINT.md, CHANGELOG.md) untuk mensinkronisasi arsitektur PostgreSQL global dan penambahan AttendanceCore."
    "v2.2.64: Standardisasi format balasan bot Telegram (Clock In, Clock Out, PLAN, PROGRESS) menggunakan waktu lokal berformat bahasa Indonesia, penyertaan nama karyawan (jika terdaftar), serta validasi lokasi GPS."
    "v2.2.65: Penolakan Clock Out sebelum 9 jam waktu kerja terpenuhi, penambahan logging diagnostik JSON payload webhook ke stdout, dan proteksi format pesan HTML dari karakter khusus."
)
