VERSION = "2.2.105"
RELEASE_DATE = "2026-07-19"
RELEASE_NOTES = (
    "v2.2.105: Menambahkan kalkulasi otomatis rentang 3 bulan untuk evaluasi baru, verifikasi pengiriman link self-assessment karyawan, serta kalkulasi dan visualisasi Indeks Akumulasi 5 pilar (Task, Performance, Training, Soft Skill, Hard Skill) di summary dan cetak PDF. "
    "v2.2.104: Memperbaiki isu double highlight pada menu navigasi sidebar dengan memperketat pencocokan url root aplikasi agar hanya aktif jika terjadi kecocokan tepat (exact match). "
    "v2.2.103: Menambahkan default akses aplikasi berupa AttendanceCore (role user) aktif secara otomatis saat user baru pertama kali terdaftar melalui login Google SSO, serta mendaftarkan role 'user' sebagai sistem role global. "
    "v2.2.102: Modifikasi pengiriman link reset password agar dikirimkan ke semua kontak unik (email, Telegram, WhatsApp) baik yang ada di tabel user maupun data karyawan terhubung, serta memunculkan tombol reset di UI jika salah satunya terisi. "
    "v2.2.101: Memperbaiki pemetaan prefix path /attendance, /project, /docs, dan /finance ke slug aplikasi yang sesuai di enforce_app_access agar user dengan hak akses dapat membuka AttendanceCore dan aplikasi terkait tanpa terblokir. "
    "v2.2.100: Perbaikan ValueError pada detail tiket SupportCore dengan menghapus inisialisasi status_map yang tidak valid dan tidak digunakan di sc_ticket_detail.html. "
    "v2.2.99: Integrasi kolom Waktu Lapor tiket dan pelacakan progress daily (% Done) tiket SupportCore ke dalam Laporan Kehadiran (Web, PDF, Excel) berdasarkan riwayat perubahan. "
    "v2.2.98: Perbaikan ValueError: 'assignee_name' is not in list pada controller at_report dengan menyertakan nama assignee pada query individual. "
    "v2.2.97: Integrasi daftar tiket/task SupportCore yang sedang dikerjakan ke dalam Laporan Kehadiran, termasuk ekspor Excel dan cetak PDF sebagai penunjang real task. "
    "v2.2.96: Penambahan pengamanan file upload berupa whitelist ekstensi dokumen & gambar serta blacklist untuk file eksekusi/skrip berbahaya (seperti php, sh, bat, exe, dll) di seluruh modul. "
    "v2.2.95: Perbaikan error sort_order is not defined saat menambahkan resource di BookingCore serta penyesuaian penanda navigasi aplikasi pada breadcrumb halaman resource BookingCore. "
    "v2.2.94: Penyesuaian kalkulasi headcount dan beban gaji karyawan kontrak dengan memisahkan kontrak aktif & berakhir serta menerapkan pembobotan fraksi hari aktif kontrak untuk beban tahunan. "
    "v2.2.93: Penambahan baris subtotal untuk masing-masing kelompok karyawan (Tetap, Kontrak, Telegram Core) di tabel gaji dan pemisahan data Telegram Core pada charts dan tables di dashboard analitik gaji. "
    "v2.2.92: Pemisahan kelompok karyawan 'Telegram Core' pada tabel gaji karyawan agar tidak tercampur dengan karyawan tetap/kontrak inti. "
    "v2.2.91: Pemisahan karyawan 'Telegram Core' dari daftar Karyawan Kontrak dan Tetap ke dalam tab terpisah di TalentCore. "
    "v2.2.90: Implementasi fitur deaktifkan massal (bulk deactivation) karyawan di dashboard TalentCore untuk mempermudah manajemen akun karyawan superadmin. "
    "v2.2.89: Penambahan menu Laporan Kehadiran mandiri di AttendanceCore dengan filter rentang tanggal, filter karyawan (untuk admin/manager), serta export data ke format Excel dan cetak PDF. "
    "v2.2.88: Penyesuaian format respon Telegram webhook untuk menyertakan nama profil Telegram di dalam tanda kurung serta menyertakan lokasi tagging dan imbauan pembuatan PLAN dan PROGRESS pada respon check-in. "
    "v2.2.87: Membatasi fitur auto-delete chat Telegram webhook agar hanya berlaku untuk command /birthday, /lapar, dan /haus saja. "
    "v2.2.86: Mengubah CHATBOT_SYSTEM prompt untuk menyertakan relasi logis skema database Hive (belajar database) dan melarang AI menampilkan query SQL teknis/raw data kepada user (user POV). "
    "v2.2.85: Implementasi tool execute_sql_query pada AI Chatbot untuk query langsung ke database PostgreSQL, penambahan petunjuk prioritasi database pada system prompt, proteksi data rahasia (gaji, password), dan peningkatan limit loop tool-calling OpenAI dari 2 ke 5. "
    "v2.2.84: Memperbaiki akses media proxy (/media/proxy) agar dibebaskan dari pembatasan hak akses aplikasi, sehingga gambar resource BookingCore dapat dibuka secara publik dan oleh user non-superadmin. "
    "v2.2.83: Menambahkan native WhatsApp webhook endpoint (/whatsapp/webhook) yang kompatibel dengan OpenWA REST API HIVE untuk mendukung absensi share location, hashtag plan/progress, dan command info otomatis di WhatsApp. "
    "v2.2.82: Menambahkan koordinat GPS asli di dalam kurung pada lokasi tagging, memperbaiki response return value JSON pada endpoint admin approval untuk mencegah pesan 'sesi berakhir' palsu, dan menambahkan toleransi parsing format jam kerja HH:MM tanpa detik. "
    "v2.2.81: Mengubah batas toleransi keterlambatan (status Terlambat) saat clock-in dari pukul 09:00 menjadi pukul 09:15, baik pada Web Portal maupun Telegram webhook. "
    "v2.2.80: Menambahkan fitur pengingat otomatis harian (setiap 5 menit sekali) untuk karyawan yang sudah clock in dan masa kerja hariannya sudah mencapai 9 jam, mengirimi notifikasi personal dan grup Telegram agar mereka tidak lupa untuk clock out. "
    "v2.2.79: Memperbaiki bug scope variable global datetime (UnboundLocalError) pada telegram webhook yang menyebabkan kegagalan respon otomatis saat menerima koordinat lokasi GPS dan tag plan/progress. "
    "v2.2.78: Refinement format respon bot Telegram untuk perintah /lapar /haus (mencantumkan tanggal lahir masing-masing) dan perintah /birthday (menampilkan seluruh daftar ulang tahun terdaftar secara berurutan tanpa limitasi waktu mendatang). "
    "v2.2.77: Memastikan semua nama pada list ulang tahun diimpor/disemai ke database karyawan (mendaftarkannya ke Telegram Core jika belum ada) agar fungsi reminder ultah tetap lengkap dan bisa dipetakan manual di kemudian hari. "
    "v2.2.76: Implementasi penjadwal otomatis reminder ulang tahun karyawan (siaran personal & grup absensi), pembersihan auto-delete 30 detik pesan bot, penyaringan pesan grup non-absen, dan antarmuka pemetaan manual Telegram ID karyawan di Web UI. "
    "v2.2.75: Menambahkan token bot Telegram fallback (dari bot lama) dan pengekstrakan chat_id yang lebih tangguh untuk custom JSON payload. "
    "v2.2.74: Implementasi reverse geocoding via OpenStreetMap Nominatim API untuk menerjemahkan lokasi GPS Telegram ke alamat teks serta pengetatan pencocokan grup check-in dan check-out. "
    "v2.2.73: Menambahkan log diagnostik dan penanganan exception pada fungsi reply di Telegram webhook untuk mempermudah pelacakan pengiriman pesan. "
    "v2.2.72: Menyertakan ID group Telegram ke dalam catatan lokasi/notes attendance, memperbaiki bug NameError 'user_mention' pada respon start/help/absen, dan menampilkan detail ID grup pada balasan command di grup yang sama. "
    "v2.2.71: Perbaikan role saving agar app-scoped (tidak menimpa app lain) dan penambahan default at_view/at_manage ke sistem role defaults saat startup/seeding. "
    "v2.2.70: Fix at_require helper in AttendanceCore to check permissions via get_db() has_permission instead of unpopulated session['user_permissions']. "
    "v2.2.69: Perubahan mass add akses menggunakan data karyawan (auto-create user account dengan key email dan default password hive2026, sso untuk @mmi-pt.com, login support username/email). "
    "v2.2.68: Hapus checkbox legacy permission di portal_roles (diganti auto-derive) dan tambah fitur mass add akses aplikasi di portal_settings. "
    "v2.2.67: Fix issue UndefinedColumn/UniqueViolation pada PostgreSQL saat penyimpanan menu role di portal_roles. "
    "v2.2.66: Pembenahan sistem Role & Permission menggunakan menu dan child menu dinamis dari database serta antarmuka Drag n Drop di Portal. "
    "v2.2.0: Objektifikasi penilaian — difficulty task, self_assigned flag, "
    "peer review 5 dimensi, benchmark per grade, AI summary (Ollama), "
    "dashboard Performa Divisi dengan peak/low/overload detection. "
    "v2.2.1: Panel Analisa Sistem di Review Evaluasi; export Excel/PDF; "
    "hapus tombol Lihat Gaji dari tabel karyawan. "
    "v2.2.2: Auto-fill Project Performance dari ProjectCore/SupportCore/POC; "
    "Ability AI Suggest berbasis data sistem (task score, difficulty, customer, POC); "
    "fix Hard Skill error 500 (ROUND::numeric PostgreSQL); "
    "fix evaluasi review_status draft → self_filled/approved; "
    "fix period_start → task_date_from di eval_review route. "
    "v2.2.3: Global error handler 500 → audit_errors; /admin/error-log page; "
    "fix due_date::date cast, self_assigned=1, pc_projects done_issues subquery. "
    "v2.2.4: Autofill Project — status proyek mapped ke DONE/ONPROGRESS/CANCELLED; "
    "Top Task: ranked list per project+customer by task/tiket count; "
    "Improvement: satu baris per POC/presales + 2 baris manual input kosong. "
    "v2.2.5: Perbaikan bug pencarian query cari_aset pada AI Chatbot agar mendukung kolom database yang valid. "
    "v2.2.6: Memperbaiki error NoneType not subscriptable pada halaman profil jika user dihapus or tidak aktif. "
    "v2.2.7: Menambahkan opsi --reset-superadmin pada script deploy-ubuntu.sh untuk melakukan reset password superadmin. "
    "v2.2.8: Memperbaiki pemuatan variabel lingkungan (.env) saat menjalankan reset password superadmin. "
    "v2.2.9: Memperbaiki SyntaxError di PostgreSQL pada halaman Infrastruktur Aset dan Lisensi Aset akibat tanda kutip ganda. "
    "v2.2.10: Menghapus menu dan rute error log yang redundan di TalentCore (digantikan oleh Audit Trail Portal). "
    "v2.2.11: Mengubah HelpdeskCore menjadi AttendanceCore dengan fitur live attendance, leave, overtime, dan correction. "
    "v2.2.12: Menambahkan integrasi Telegram Bot untuk melakukan absensi (Clock In / Clock Out) dengan mengirimkan lokasi (Send Location). "
    "v2.2.13: Peningkatan ketahanan Webhook Telegram (case-insensitive username, edited_message) and integrasi perbaikan/error-handling pencatatan lokasi di Web UI. "
    "v2.2.14: Memperbaiki pencocokan identitas user Telegram di Webhook saat mengirim lokasi di dalam grup dengan memetakan user.id (sender) alih-alih chat.id (group ID). "
    "v2.2.15: Mewajibkan strict Geolocation GPS pada Clock In dan Clock Out Web Attendance Core (tanialah koordinat kosong) and menghapus input catatan. "
    "v2.2.16: Integrasi PLAN and PROGRESS dari Telegram Bot ke modul Presensi Harian (AttendanceCore) dengan tampilan UI detail modal. "
    "v2.2.17: Menghapus secara permanen record registrasi aplikasi obsolete (HelpdeskCore) dari database superapp_apps saat inisialisasi aplikasi. "
    "v2.2.18: Memperbaiki konversi datetime SQLite ke PostgreSQL untuk query AssetCore and penanganan duplicate username agar kompatibel dengan psycopg2. "
    "v2.2.19: Menambahkan modul Backup Center di Portal untuk backup source code aplikasi, konten uploads, dan database dengan pengiriman email, upload S3, download langsung, dan scheduler. "
    "v2.2.20: Memperbaiki kegagalan manual backup PostgreSQL akibat program pg_dump tidak ditemukan dengan menambahkan dependency postgresql-client dan dukungan kustom PG_DUMP_PATH. "
    "v2.2.21: Memperbaiki bug status backup yang tidak terupdate ('Belum Pernah Run') di PostgreSQL karena transaction rollback akibat kegagalan query dengan RETURNING id pada tabel app_settings. "
    "v2.2.22: Menambahkan manual loader untuk berkas .env pada inisialisasi awal app.py agar DB_TYPE terdeteksi sesuai (PostgreSQL) serta menambahkan prefix folder backups/ pada upload S3. "
    "v2.2.23: Implementasi script backup_db.sh terpisah untuk backup PostgreSQL dengan credential env/admin, fitur hapus backup langsung, dan batas retensi housekeeping lokal. "
    "v2.2.24: Menambahkan perbaikan environment PATH di evaluasi.service and script backup_db.sh untuk mengatasi error command not found (dirname, grep, xargs, pg_dump). "
    "v2.2.25: Mengaktifkan default auto backup lokal & S3 di DEFAULT_SETTINGS, serta mendukung opsi penyimpanan konten media (static/uploads) ke S3 (folder upload/media/). "
    "v2.2.26: Memperbaiki bug 0-byte image upload akibat stream consumption dan timeout/Gunicorn restart saat S3 enabled tapi credentials kosong/koneksi lambat. "
    "v2.2.27: Implementasi rute media proxy (/media/proxy/<path:key>) untuk mengamankan data S3 tetap private dengan streaming file media secara terotentikasi. "
    "v2.2.28: Memindahkan rute media_proxy ke posisi setelah definisi login_required di app.py untuk mengatasi NameError saat boot. "
    "v2.2.29: Memperbaiki bug nested forms pada template edit resource BookingCore, mengaktifkan AJAX image deletion, dan mendukung multi-upload gallery saat menambahkan resource. "
    "v2.2.30: Memperbaiki TemplateSyntaxError (stray endif tag) di booking_resource_edit.html setelah pembersihan nested forms. "
    "v2.2.31: Menambahkan tampilan dashboard BookingCore berformat kalender bulanan lengkap dengan detail jadwal resources dan pemesan. "
    "v2.2.32: Sinkronisasi kalender bulanan BookingCore dengan libur nasional Indonesia dan cuti bersama menggunakan REST API. "
    "v2.2.33: Mengubah informasi booking di dalam kalender bulanan BookingCore agar menampilkan nama Resource, Jam Booking, dan Pemesan. "
    "v2.2.34: Memperbaiki bug input is_active yang terlewat saat proses penambahan resource baru di BookingCore. "
    "v2.2.35: Implementasi Media Library Selector untuk memilih media terunggah (local/S3), folder penyimpanan bookingcore khusus, dan fitur hapus resource secara permanen. "
    "v2.2.36: Implementasi Public Booking Dashboard (/booking/public) tanpa otentikasi login, dengan visualisasi TV Monitor modern, live clock, auto-refresh, dan S3 media public bypass untuk file resource. "
    "v2.2.37: Memperbaiki error UndefinedColumn start_time/end_time di PostgreSQL dengan mengubahnya ke start_dt/end_dt, dan menyertakan JOIN JOIN users untuk memuat nama pemesan. "
    "v2.2.38: Menambahkan kategori sidebar 'Lainnya' untuk menampilkan equipment (Proyektor Portable), dan memperkuat visual/kontras TV display agar lebih enterprise-grade. "
    "v2.2.39: Implementasi fitur Request Alat Kerja (Laptop) di AssetCore dengan input admin PIC untuk tipe, spesifikasi, link pembelian online, dan estimasi harga. "
    "v2.2.40: Perluasan form Request Alat Kerja sesuai format pembelian laptop, spek opsional CPU/RAM/disk, dan auto-create asset Laptop/PC saat request Completed dengan kompatibilitas PostgreSQL. "
    "v2.2.41: Menambahkan requested-by channel pada Request Alat Kerja serta multi attachment untuk capture request dan foto unit pembelian/checking. "
    "v2.2.42: Memperbaiki otorisasi AssetCore (dan core lainnya) agar mendeteksi role spesifik aplikasi (app_role dari user_app_access) dan menggabungkannya ke user_perms. "
    "v2.2.43: Mengunci request alat kerja yang Completed (greyed out & disabled) serta menghubungkan detail asset & list asset dengan info request alat kerja asal. "
    "v2.2.44: Menambahkan requestor name, mengubah label Tanggal Masuk menjadi Tanggal Proses IT Support, serta implementasi master hardware specs/software dengan combo datalist. "
    "v2.2.45: Redesain halaman Laporan & Analitik SupportCore dengan visualisasi modern ala Meridian (KPI Cards dan interactive charts dengan ApexCharts). "
    "v2.2.46: Memperbaiki ValueError tool_request_id is not in list pada daftar asset dengan menambahkan query tool_request_id di route ac_assets. "
    "v2.2.47: Memperbaiki ValueError loop unpacking too many values to unpack (expected 2) pada data serialisasi templates/sc_reports.html. "
    "v2.2.48: Peningkatan dan redesain layout/tema HIVE secara global ke gaya Meridian (Stisla V3) menggunakan font Inter, light-sidebar premium dengan aksen ungu, serta card & input modern. "
    "v2.2.49: Menambahkan toggle minimize/maximize sidebar menu pada tampilan desktop menggunakan HTML5 localStorage persistence. "
    "v2.2.50: Menyembunyikan seluruh teks link menu sidebar saat diminimize (menampilkan ikon saja), menghapus user dropdown dari sidebar, dan menyatukannya ke dropdown user di header atas. "
    "v2.2.51: Menambahkan validasi wajib upload bukti attachment (capture approval/rejection) saat status Request Alat Kerja dirubah ke Approved atau Rejected, baik di sisi client (browser) maupun server. "
    "v2.2.52: Menambahkan validasi wajib upload bukti serah terima perangkat (BAST/foto) saat status Request Alat Kerja dirubah ke Completed, baik di sisi client maupun server. "
    "v2.2.53: Memperbaiki error read timed out pada notifikasi Telegram AssetCore dengan mengurangi timeout dari 10s ke 5s dan mengirim notifikasi fire-and-forget secara non-blocking di background thread. "
    "v2.2.54: Menambahkan tombol manual trigger form review evaluasi karyawan di halaman Manajemen Karyawan (kontrak & tetap), dengan modal konfirmasi periode dan pengiriman link self-assessment otomatis via email/Telegram. "
    "v2.2.55: Menyempurnakan Telegram Webhook AttendanceCore agar mendukung group/private chat location tagging, validasi minimal 10 karakter untuk #PLAN dan #PROGRESS (bersih dari tag), dan memblokir Clock Out sampai plan & progress lengkap. "
    "v2.2.56: Memperbaiki deteksi user Telegram dengan mengecek tabel users dan employees, serta memindahkan respons bot ke Telegram agar dikirim terlebih dahulu sebelum proses tulis database (commit). "
    "v2.2.57: Menghapus total dukungan database SQLite dan mematikan fallback local database SQLite, memaksa penggunaan database PostgreSQL secara penuh (global default)."
    "v2.2.58: Menambahkan dukungan kompatibilitas terhadap custom JSON payload yang dikirimkan oleh Node.js helper bot (Telegraf location forwarder)."
    "v2.2.59: Menambahkan tabel Status Kehadiran Karyawan Hari Ini (Live Attendance Wall) pada dashboard AttendanceCore untuk menampilkan informasi clock-in, clock-out, lokasi, plan, dan progress seluruh karyawan."
    "v2.2.60: Pengetatan alur presensi Telegram: Rencana kerja (#PLAN) tidak dapat diisi sebelum Clock In, laporan kemajuan (#PROGRESS) tidak dapat diisi sebelum #PLAN lengkap, dan Clock Out diblokir hingga keduanya diisi secara terpisah."
    "v2.2.61: Menambahkan informasi nama Telegram Group pengirim absensi serta kolom kalkulasi Durasi Kerja (jam) hasil selisih Clock Out dan Clock In pada tabel Live Attendance Wall."
    "v2.2.62: Memperbaiki prioritas deteksi Telegram ID ke tabel karyawan (employees) terlebih dahulu, menambahkan auto-register fallback untuk pengguna tidak dikenal, mendukung clock-out berulang (update checkout), dan menambahkan detail nama grup pada balasan bot Telegram."
    "v2.2.63: Pemutakhiran menyeluruh dokumen repositori (README.md, BLUEPRINT.md, CHANGELOG.md) untuk mensinkronisasi arsitektur PostgreSQL global dan penambahan AttendanceCore."
    "v2.2.64: Standardisasi format balasan bot Telegram (Clock In, Clock Out, PLAN, PROGRESS) menggunakan waktu lokal berformat bahasa Indonesia, penyertaan nama karyawan (jika terdaftar), serta validasi lokasi GPS."
    "v2.2.65: Penolakan Clock Out sebelum 9 jam waktu kerja terpenuhi, penambahan logging diagnostik JSON payload webhook ke stdout, dan proteksi format pesan HTML dari karakter khusus."
)
