VERSION = "2.2.37"
RELEASE_DATE = "2026-07-08"
RELEASE_NOTES = (
    "v2.2.0: Objektifikasi penilaian — difficulty task, self_assigned flag, "
    "peer review 5 dimensi, benchmark per grade, AI summary (Ollama), "
    "dashboard Performa Divisi dengan peak/low/overload detection. "
    "v2.2.1: Panel Analisa Sistem di Review Evaluasi; export Excel/PDF; "
    "hapus tombol Lihat Gaji dari tabel karyawan. "
    "v2.2.2: Auto-fill Project Performance dari ProjectCore/SupportCore/POC; "
    "Ability AI Suggest berbasis data sistem (task score, difficulty, customer, POC); "
    "fix Hard Skill error 500 (ROUND::numeric PostgreSQL); "
    "fix evaluasi review_status draft → self_filled/approved; "
    "fix period_start → task_date_from di eval_review route. "
    "v2.2.3: Global error handler 500 → audit_errors; /admin/error-log page; "
    "fix due_date::date cast, self_assigned=1, pc_projects done_issues subquery. "
    "v2.2.4: Autofill Project — status proyek mapped ke DONE/ONPROGRESS/CANCELLED; "
    "Top Task: ranked list per project+customer by task/tiket count; "
    "Improvement: satu baris per POC/presales + 2 baris manual input kosong. "
    "v2.2.5: Perbaikan bug pencarian query cari_aset pada AI Chatbot agar mendukung kolom database yang valid. "
    "v2.2.6: Memperbaiki error NoneType not subscriptable pada halaman profil jika user dihapus atau tidak aktif. "
    "v2.2.7: Menambahkan opsi --reset-superadmin pada script deploy-ubuntu.sh untuk melakukan reset password superadmin. "
    "v2.2.8: Memperbaiki pemuatan variabel lingkungan (.env) saat menjalankan reset password superadmin. "
    "v2.2.9: Memperbaiki SyntaxError di PostgreSQL pada halaman Infrastruktur Aset dan Lisensi Aset akibat tanda kutip ganda. "
    "v2.2.10: Menghapus menu dan rute error log yang redundan di TalentCore (digantikan oleh Audit Trail Portal). "
    "v2.2.11: Mengubah HelpdeskCore menjadi AttendanceCore dengan fitur live attendance, leave, overtime, dan correction. "
    "v2.2.12: Menambahkan integrasi Telegram Bot untuk melakukan absensi (Clock In / Clock Out) dengan mengirimkan lokasi (Send Location). "
    "v2.2.13: Peningkatan ketahanan Webhook Telegram (case-insensitive username, edited_message) and integrasi perbaikan/error-handling pencatatan lokasi di Web UI. "
    "v2.2.14: Memperbaiki pencocokan identitas user Telegram di Webhook saat mengirim lokasi di dalam grup dengan memetakan user.id (sender) alih-alih chat.id (group ID). "
    "v2.2.15: Mewajibkan strict Geolocation GPS pada Clock In dan Clock Out Web Attendance Core (tanpa fallback koordinat kosong) and menghapus input catatan. "
    "v2.2.16: Integrasi PLAN and PROGRESS dari Telegram Bot ke modul Presensi Harian (AttendanceCore) dengan tampilan UI detail modal. "
    "v2.2.17: Menghapus secara permanen record registrasi aplikasi obsolete (HelpdeskCore) dari database superapp_apps saat inisialisasi aplikasi. "
    "v2.2.18: Memperbaiki konversi datetime SQLite ke PostgreSQL untuk query AssetCore and penanganan duplicate username agar kompatibel dengan psycopg2. "
    "v2.2.19: Menambahkan modul Backup Center di Portal untuk backup source code aplikasi, konten uploads, dan database dengan pengiriman email, upload S3, download langsung, dan scheduler. "
    "v2.2.20: Memperbaiki kegagalan manual backup PostgreSQL akibat program pg_dump tidak ditemukan dengan menambahkan dependency postgresql-client dan dukungan kustom PG_DUMP_PATH. "
    "v2.2.21: Memperbaiki bug status backup yang tidak terupdate ('Belum Pernah Run') di PostgreSQL karena transaction rollback akibat kegagalan query dengan RETURNING id pada tabel app_settings. "
    "v2.2.22: Menambahkan manual loader untuk berkas .env pada inisialisasi awal app.py agar DB_TYPE terdeteksi sesuai (PostgreSQL) serta menambahkan prefix folder backups/ pada upload S3. "
    "v2.2.23: Implementasi script backup_db.sh terpisah untuk backup PostgreSQL dengan credential env/admin, fitur hapus backup langsung, dan batas retensi housekeeping lokal. "
    "v2.2.24: Menambahkan perbaikan environment PATH di evaluasi.service and script backup_db.sh untuk mengatasi error command not found (dirname, grep, xargs, pg_dump). "
    "v2.2.25: Mengaktifkan default auto backup lokal & S3 di DEFAULT_SETTINGS, serta mendukung opsi penyimpanan konten media (static/uploads) ke S3 (folder upload/media/). "
    "v2.2.26: Memperbaiki bug 0-byte image upload akibat stream consumption dan timeout/Gunicorn restart saat S3 enabled tapi credentials kosong/koneksi lambat. "
    "v2.2.27: Implementasi rute media proxy (/media/proxy/<path:key>) untuk mengamankan data S3 tetap private dengan streaming file media secara terotentikasi. "
    "v2.2.28: Memindahkan rute media_proxy ke posisi setelah definisi login_required di app.py untuk mengatasi NameError saat boot. "
    "v2.2.29: Memperbaiki bug nested forms pada template edit resource BookingCore, mengaktifkan AJAX image deletion, dan mendukung multi-upload gallery saat menambahkan resource. "
    "v2.2.30: Memperbaiki TemplateSyntaxError (stray endif tag) di booking_resource_edit.html setelah pembersihan nested forms. "
    "v2.2.31: Menambahkan tampilan dashboard BookingCore berformat kalender bulanan lengkap dengan detail jadwal resources dan pemesan. "
    "v2.2.32: Sinkronisasi kalender bulanan BookingCore dengan libur nasional Indonesia dan cuti bersama menggunakan REST API. "
    "v2.2.33: Mengubah informasi booking di dalam kalender bulanan BookingCore agar menampilkan nama Resource, Jam Booking, dan Pemesan. "
    "v2.2.34: Memperbaiki bug input is_active yang terlewat saat proses penambahan resource baru di BookingCore. "
    "v2.2.35: Implementasi Media Library Selector untuk memilih media terunggah (local/S3), folder penyimpanan bookingcore khusus, dan fitur hapus resource secara permanen. "
    "v2.2.36: Implementasi Public Booking Dashboard (/booking/public) tanpa otentikasi login, dengan visualisasi TV Monitor modern, live clock, auto-refresh, dan S3 media public bypass untuk file resource. "
    "v2.2.37: Memperbaiki error UndefinedColumn start_time/end_time di PostgreSQL dengan mengubahnya ke start_dt/end_dt, dan menyertakan JOIN users untuk memuat nama pemesan."
)
